name: Run tests on any Push event
# Запуск при любом push евенте в любой ветке
on: [push]
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      # Чекаутим код
      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install -r requirements.txt
      - name: Linting
        run: ./scripts/lint
      - name: Run tests
        run: ./scripts/test
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          file: .coverage
          github-token: ${{ secrets.GITHUB_TOKEN }}
